"""your message

Revision ID: 8314ea8490a6
Revises: 275586a7bef6
Create Date: 2024-08-22 16:48:43.692536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8314ea8490a6'
down_revision = '275586a7bef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
